apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
 name: "torch-pred-gs"
spec:
 predictor:
   pytorch:
     protocolVersion: v2
     storageUri: "gs://kfserving-examples/models/torchserve/image_classifier"
