tracking_issue: 2724

# List of workflows that will be re-run in case of failures
# https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/retryBot.ts
retryable_workflows:
- Push Docker
- Run Regression
- Push torchserve
- Docker CI
- CI
- Benchmark  
