logger: logging.Logger = ...
CLEANUP_REGEX: typing.Pattern[str] = ...
CONTRACTIONS_PATTERN: typing.Pattern[str] = ...
class TextHandler:
    def __init__(self) -> None: ...
    def _expand_contractions(self, text) -> str: ...
    def _remove_accented_characters(self, text) -> str: ...
    def initialize(self, context) -> None: ...

