def cleanup_model_store() -> None: ...
def move_logs(log_file: typing.Union[os.PathLike[bytes], os.PathLike[str], bytes, str], artifact_dir) -> None: ...
def test_api(collection: str) -> None: ...
def trigger_all() -> int: ...
def trigger_explanation_tests() -> int: ...
def trigger_https_tests() -> int: ...
def trigger_https_tests_kf() -> int: ...
def trigger_https_tests_kfv2() -> int: ...
def trigger_incr_timeout_inference_tests() -> int: ...
def trigger_inference_tests() -> int: ...
def trigger_inference_tests_kf() -> int: ...
def trigger_inference_tests_kfv2() -> int: ...
def trigger_management_tests() -> int: ...
def trigger_management_tests_kf() -> int: ...
def trigger_workflow_inference_tests() -> int: ...
def trigger_workflow_tests() -> int: ...
