def clean_slate() -> None: ...
def clean_up_build_residuals() -> None: ...
def install_from_src() -> None: ...
def install_torch_model_archiver() -> None: ...
def install_torch_workflow_archiver() -> None: ...
def install_torchserve() -> None: ...
