args: argparse.Namespace = ...
def install_dependencies(cuda_version=None) -> None: ...
class Common:
    def __init__(self) -> None: ...
    def install_java(self) -> None: ...
    def install_jmeter(self) -> None: ...
    def install_node_packages(self) -> None: ...
    def install_nodejs(self) -> None: ...
    def install_python_packages(self, cuda_version, requirements_file_path) -> None: ...
    def install_torch_packages(self, cuda_version) -> None: ...
    def install_wget(self) -> None: ...

class Darwin:
    def __init__(self) -> None: ...
    def install_java(self) -> None: ...
    def install_node_packages(self) -> None: ...
    def install_nodejs(self) -> None: ...
    def install_wget(self) -> None: ...

class Linux:
    def __init__(self) -> None: ...
    def install_java(self) -> None: ...
    def install_libgit2(self) -> None: ...
    def install_maven(self) -> None: ...
    def install_nodejs(self) -> None: ...
    def install_wget(self) -> None: ...

class Windows:
    def __init__(self) -> None: ...
    def install_java(self) -> None: ...
    def install_nodejs(self) -> None: ...
    def install_wget(self) -> None: ...

