args: argparse.Namespace = ...
def delete_model_store_gen_dir() -> None: ...
def gen_mar(model_store=None) -> None: ...
def generate_mars(mar_config=MAR_CONFIG_FILE_PATH, model_store_dir=MODEL_STORE_DIR) -> None: ...
def model_archiver_command_builder(model_name=None, version=None, model_file=None, serialized_file=None, handler=None, extra_files=None, runtime=None, archive_format=None, requirements_file=None, export_path=None, force: bool = True) -> str: ...
