env_info_fmt: str = ...
torchserve_branch: str = ...
def get_nvidia_smi() -> str: ...
def get_platform() -> str: ...
def get_torch_model_archiver() -> str: ...
def get_torchserve_version() -> str: ...
def main(branch_name) -> None: ...
def populate_cuda_env(cuda_available_str) -> None: ...
def populate_env_info() -> None: ...
def populate_java_env() -> None: ...
def populate_npm_env() -> None: ...
def populate_os_env() -> None: ...
def populate_python_env(pip_version, pip_list_output) -> None: ...
def populate_torchserve_env(torch_pkg) -> None: ...
