def download_save(url: typing.Union[bytes, str], path=None, filename=None) -> None: ...
def rm_dir(path: typing.Union[os.PathLike[str], bytes, str]) -> None: ...
def rm_file(path: typing.Union[os.PathLike[bytes], os.PathLike[str], bytes, str], regex: bool = False) -> None: ...
def unzip(filename: typing.Union[os.PathLike[str], str], destination: typing.Union[None, os.PathLike[str], str], arc_type: typing.Optional[str]) -> None: ...
