# Each model can have multiple inputs
# Each input has a dtype, device and shape
# Some shapes can be arbitrary like a positive integer for batch size

# BERT model (not tested)
input:
  dtype: "float16" # Extend this to a list later
  device: "gpu"
  shape: [-1, 3, 7, 7] # the first element is the batch size

input:
  dtype: "int"
  device: "gpu"
  shape : [-1]