logger: logging.Logger = ...
_NumpyToDatatype: typing.Dict[str, str] = ...
class KServev2Envelope:
    def _to_json(self, data) -> typing.Dict[str, typing.Any]: ...
    def format_output(self, data) -> typing.List[typing.Dict[str, typing.Any]]: ...

