def logs_created(no_config_snapshots: bool = False) -> None: ...
def run_log_location_var(custom_path: typing.Union[os.PathLike[bytes], os.PathLike[str], bytes, int, str] = test_utils.ROOT_DIR, no_config_snapshots: bool = False) -> None: ...
def run_metrics_location_var(custom_path: typing.Union[os.PathLike[bytes], os.PathLike[str], bytes, int, str] = test_utils.ROOT_DIR, no_config_snapshots: bool = False) -> None: ...
def setup_module(module) -> None: ...
def teardown_module(module) -> None: ...
def test_async_logging() -> None: ...
def test_async_logging_non_boolean() -> None: ...
def test_log_location_and_metric_location_vars_snapshot_enabled() -> None: ...
def test_log_location_var_snapshot_disabled() -> None: ...
def test_log_location_var_snapshot_disabled_custom_path_read_only() -> None: ...
def test_log_location_var_snapshot_enabled() -> None: ...
def test_logs_created() -> None: ...
def test_logs_startup_cfg_created_snapshot_disabled() -> None: ...
def test_logs_startup_cfg_created_snapshot_enabled() -> None: ...
def test_metrics_location_var_snapshot_disabled() -> None: ...
def test_metrics_location_var_snapshot_enabled() -> None: ...
def test_metrics_location_var_snapshot_enabled_rdonly_dir() -> None: ...
def test_metrics_startup_cfg_created_snapshot_disabled() -> None: ...
def test_metrics_startup_cfg_created_snapshot_enabled() -> None: ...
def validate_metrics_created(no_config_snapshots: bool = False) -> None: ...
