def clean_mar_file(mar_name) -> None: ...
def create_resnet_archive(model_name: str = "resnset-18", version: str = "1.0", force: bool = False) -> int: ...
def setup_module(module) -> None: ...
def teardown_module(module) -> None: ...
def test_duplicate_model_registration_using_http_url_followed_by_local_url() -> None: ...
def test_duplicate_model_registration_using_local_url_followed_by_http_url() -> None: ...
def test_model_archiver_to_regenerate_model_mar_with_force() -> None: ...
def test_model_archiver_to_regenerate_model_mar_without_force() -> None: ...
def test_model_archiver_without_handler_flag() -> None: ...
def test_model_archiver_without_model_file_flag() -> None: ...
def test_model_archiver_without_model_name_flag() -> None: ...
def test_model_archiver_without_serialized_flag() -> None: ...
def test_multiple_model_versions_registration() -> None: ...
