def replace_mar_file_with_dummy_mar_in_model_store(model_store=None, model_mar=None) -> None: ...
def setup_module(module) -> None: ...
def snapshot_created_on_management_api_invoke(model_mar: str = "densenet161.mar") -> None: ...
def teardown_module(module) -> None: ...
def test_no_config_snapshots_cli_option() -> None: ...
def test_replace_mar_file_with_dummy() -> None: ...
def test_restart_torchserve_with_last_snapshot_with_model_mar_removed() -> None: ...
def test_restart_torchserve_with_one_of_model_mar_removed() -> None: ...
def test_snapshot_created_on_management_api_invoke() -> None: ...
def test_snapshot_created_on_start_and_stop() -> None: ...
def test_start_from_default() -> None: ...
def test_start_from_latest() -> None: ...
def test_start_from_non_existing_snapshot() -> None: ...
def test_start_from_read_only_snapshot() -> None: ...
def test_start_from_snapshot() -> None: ...
def test_torchserve_init_with_non_existent_model_store() -> None: ...
