def crate_mar_file_table() -> None: ...
def delete_all_snapshots() -> None: ...
def delete_mar_file_from_model_store(model_store=None, model_mar=None) -> None: ...
def delete_model_store(model_store=None) -> None: ...
def model_archiver_command_builder(model_name=None, version=None, model_file=None, serialized_file=None, handler=None, extra_files=None, force: bool = False) -> str: ...
def register_model_with_params(params) -> requests.models.Response: ...
def start_torchserve(model_store=None, snapshot_file=None, no_config_snapshots: bool = False, gen_mar: bool = True) -> None: ...
def stop_torchserve() -> None: ...
def torchserve_cleanup() -> None: ...
def unregister_model(model_name) -> requests.models.Response: ...
