def set_custom_handler(handler_name) -> None: ...
def test_batch_input(set_custom_handler, handler_name) -> None: ...
def test_profiler_arguments_override(set_custom_handler, handler_name) -> None: ...
def test_profiler_default_and_custom_handler(set_custom_handler, handler_name) -> None: ...
