apiVersion: v1
kind: Service
metadata:
  name: ts-def
  labels:
    run: ts-def
spec:
  type: NodePort
  selector:
    app: ts-def
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: inference
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: management
