class TestWorkflowPackaging:
    def patches(self, mocker) -> workflow-archiver.workflow_archiver.tests.unit_tests.test_workflow_packaging.TestWorkflowPackaging.patches.Patches: ...
    def test_export_workflow_method(self, patches) -> None: ...
    def test_gen_workflow_archive(self, patches) -> None: ...

