// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: management.proto

package org.pytorch.serve.grpc.management;

public final class Management {
  private Management() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_pytorch_serve_grpc_management_ManagementResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_pytorch_serve_grpc_management_ManagementResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_pytorch_serve_grpc_management_DescribeModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_pytorch_serve_grpc_management_DescribeModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_pytorch_serve_grpc_management_ListModelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_pytorch_serve_grpc_management_ListModelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_pytorch_serve_grpc_management_SetDefaultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_pytorch_serve_grpc_management_SetDefaultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_pytorch_serve_grpc_management_UnregisterModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_pytorch_serve_grpc_management_UnregisterModelRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020management.proto\022!org.pytorch.serve.gr" +
      "pc.management\"!\n\022ManagementResponse\022\013\n\003m" +
      "sg\030\001 \001(\t\"A\n\024DescribeModelRequest\022\022\n\nmode" +
      "l_name\030\001 \001(\t\022\025\n\rmodel_version\030\002 \001(\t\";\n\021L" +
      "istModelsRequest\022\r\n\005limit\030\001 \001(\005\022\027\n\017next_" +
      "page_token\030\002 \001(\005\"\316\001\n\024RegisterModelReques" +
      "t\022\022\n\nbatch_size\030\001 \001(\005\022\017\n\007handler\030\002 \001(\t\022\027" +
      "\n\017initial_workers\030\003 \001(\005\022\027\n\017max_batch_del" +
      "ay\030\004 \001(\005\022\022\n\nmodel_name\030\005 \001(\t\022\030\n\020response" +
      "_timeout\030\006 \001(\005\022\017\n\007runtime\030\007 \001(\t\022\023\n\013synch" +
      "ronous\030\010 \001(\010\022\013\n\003url\030\t \001(\t\"\241\001\n\022ScaleWorke" +
      "rRequest\022\022\n\nmodel_name\030\001 \001(\t\022\025\n\rmodel_ve" +
      "rsion\030\002 \001(\t\022\022\n\nmax_worker\030\003 \001(\005\022\022\n\nmin_w" +
      "orker\030\004 \001(\005\022\022\n\nnumber_gpu\030\005 \001(\005\022\023\n\013synch" +
      "ronous\030\006 \001(\010\022\017\n\007timeout\030\007 \001(\005\">\n\021SetDefa" +
      "ultRequest\022\022\n\nmodel_name\030\001 \001(\t\022\025\n\rmodel_" +
      "version\030\002 \001(\t\"C\n\026UnregisterModelRequest\022" +
      "\022\n\nmodel_name\030\001 \001(\t\022\025\n\rmodel_version\030\002 \001" +
      "(\t2\240\006\n\025ManagementAPIsService\022\201\001\n\rDescrib" +
      "eModel\0227.org.pytorch.serve.grpc.manageme" +
      "nt.DescribeModelRequest\0325.org.pytorch.se" +
      "rve.grpc.management.ManagementResponse\"\000" +
      "\022{\n\nListModels\0224.org.pytorch.serve.grpc." +
      "management.ListModelsRequest\0325.org.pytor" +
      "ch.serve.grpc.management.ManagementRespo" +
      "nse\"\000\022\201\001\n\rRegisterModel\0227.org.pytorch.se" +
      "rve.grpc.management.RegisterModelRequest" +
      "\0325.org.pytorch.serve.grpc.management.Man" +
      "agementResponse\"\000\022}\n\013ScaleWorker\0225.org.p" +
      "ytorch.serve.grpc.management.ScaleWorker" +
      "Request\0325.org.pytorch.serve.grpc.managem" +
      "ent.ManagementResponse\"\000\022{\n\nSetDefault\0224" +
      ".org.pytorch.serve.grpc.management.SetDe" +
      "faultRequest\0325.org.pytorch.serve.grpc.ma" +
      "nagement.ManagementResponse\"\000\022\205\001\n\017Unregi" +
      "sterModel\0229.org.pytorch.serve.grpc.manag" +
      "ement.UnregisterModelRequest\0325.org.pytor" +
      "ch.serve.grpc.management.ManagementRespo" +
      "nse\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_pytorch_serve_grpc_management_ManagementResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_pytorch_serve_grpc_management_ManagementResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_pytorch_serve_grpc_management_ManagementResponse_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_org_pytorch_serve_grpc_management_DescribeModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_pytorch_serve_grpc_management_DescribeModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_pytorch_serve_grpc_management_DescribeModelRequest_descriptor,
        new java.lang.String[] { "ModelName", "ModelVersion", });
    internal_static_org_pytorch_serve_grpc_management_ListModelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_pytorch_serve_grpc_management_ListModelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_pytorch_serve_grpc_management_ListModelsRequest_descriptor,
        new java.lang.String[] { "Limit", "NextPageToken", });
    internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_descriptor,
        new java.lang.String[] { "BatchSize", "Handler", "InitialWorkers", "MaxBatchDelay", "ModelName", "ResponseTimeout", "Runtime", "Synchronous", "Url", });
    internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_descriptor,
        new java.lang.String[] { "ModelName", "ModelVersion", "MaxWorker", "MinWorker", "NumberGpu", "Synchronous", "Timeout", });
    internal_static_org_pytorch_serve_grpc_management_SetDefaultRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_pytorch_serve_grpc_management_SetDefaultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_pytorch_serve_grpc_management_SetDefaultRequest_descriptor,
        new java.lang.String[] { "ModelName", "ModelVersion", });
    internal_static_org_pytorch_serve_grpc_management_UnregisterModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_pytorch_serve_grpc_management_UnregisterModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_pytorch_serve_grpc_management_UnregisterModelRequest_descriptor,
        new java.lang.String[] { "ModelName", "ModelVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
