// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: management.proto

package org.pytorch.serve.grpc.management;

public interface ManagementResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.pytorch.serve.grpc.management.ManagementResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Response string of different management API calls.
   * </pre>
   *
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <pre>
   * Response string of different management API calls.
   * </pre>
   *
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
