// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: management.proto

package org.pytorch.serve.grpc.management;

public interface RegisterModelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.pytorch.serve.grpc.management.RegisterModelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Inference batch size, default: 1.
   * </pre>
   *
   * <code>int32 batch_size = 1;</code>
   * @return The batchSize.
   */
  int getBatchSize();

  /**
   * <pre>
   * Inference handler entry-point. This value will override handler in MANIFEST.json if present.
   * </pre>
   *
   * <code>string handler = 2;</code>
   * @return The handler.
   */
  java.lang.String getHandler();
  /**
   * <pre>
   * Inference handler entry-point. This value will override handler in MANIFEST.json if present.
   * </pre>
   *
   * <code>string handler = 2;</code>
   * @return The bytes for handler.
   */
  com.google.protobuf.ByteString
      getHandlerBytes();

  /**
   * <pre>
   * Number of initial workers, default: 0.
   * </pre>
   *
   * <code>int32 initial_workers = 3;</code>
   * @return The initialWorkers.
   */
  int getInitialWorkers();

  /**
   * <pre>
   * Maximum delay for batch aggregation, default: 100.
   * </pre>
   *
   * <code>int32 max_batch_delay = 4;</code>
   * @return The maxBatchDelay.
   */
  int getMaxBatchDelay();

  /**
   * <pre>
   * Name of model. This value will override modelName in MANIFEST.json if present.
   * </pre>
   *
   * <code>string model_name = 5;</code>
   * @return The modelName.
   */
  java.lang.String getModelName();
  /**
   * <pre>
   * Name of model. This value will override modelName in MANIFEST.json if present.
   * </pre>
   *
   * <code>string model_name = 5;</code>
   * @return The bytes for modelName.
   */
  com.google.protobuf.ByteString
      getModelNameBytes();

  /**
   * <pre>
   * Maximum time, in seconds, the TorchServe waits for a response from the model inference code, default: 120.
   * </pre>
   *
   * <code>int32 response_timeout = 6;</code>
   * @return The responseTimeout.
   */
  int getResponseTimeout();

  /**
   * <pre>
   * Runtime for the model custom service code. This value will override runtime in MANIFEST.json if present.
   * </pre>
   *
   * <code>string runtime = 7;</code>
   * @return The runtime.
   */
  java.lang.String getRuntime();
  /**
   * <pre>
   * Runtime for the model custom service code. This value will override runtime in MANIFEST.json if present.
   * </pre>
   *
   * <code>string runtime = 7;</code>
   * @return The bytes for runtime.
   */
  com.google.protobuf.ByteString
      getRuntimeBytes();

  /**
   * <pre>
   * Decides whether creation of worker synchronous or not, default: false.
   * </pre>
   *
   * <code>bool synchronous = 8;</code>
   * @return The synchronous.
   */
  boolean getSynchronous();

  /**
   * <pre>
   * Model archive download url, support local file or HTTP(s) protocol.
   * </pre>
   *
   * <code>string url = 9;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * Model archive download url, support local file or HTTP(s) protocol.
   * </pre>
   *
   * <code>string url = 9;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
