// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: management.proto

package org.pytorch.serve.grpc.management;

/**
 * Protobuf type {@code org.pytorch.serve.grpc.management.RegisterModelRequest}
 */
public final class RegisterModelRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.pytorch.serve.grpc.management.RegisterModelRequest)
    RegisterModelRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterModelRequest.newBuilder() to construct.
  private RegisterModelRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterModelRequest() {
    handler_ = "";
    modelName_ = "";
    runtime_ = "";
    url_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RegisterModelRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegisterModelRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            batchSize_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            handler_ = s;
            break;
          }
          case 24: {

            initialWorkers_ = input.readInt32();
            break;
          }
          case 32: {

            maxBatchDelay_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            modelName_ = s;
            break;
          }
          case 48: {

            responseTimeout_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            runtime_ = s;
            break;
          }
          case 64: {

            synchronous_ = input.readBool();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.pytorch.serve.grpc.management.RegisterModelRequest.class, org.pytorch.serve.grpc.management.RegisterModelRequest.Builder.class);
  }

  public static final int BATCH_SIZE_FIELD_NUMBER = 1;
  private int batchSize_;
  /**
   * <pre>
   * Inference batch size, default: 1.
   * </pre>
   *
   * <code>int32 batch_size = 1;</code>
   * @return The batchSize.
   */
  @java.lang.Override
  public int getBatchSize() {
    return batchSize_;
  }

  public static final int HANDLER_FIELD_NUMBER = 2;
  private volatile java.lang.Object handler_;
  /**
   * <pre>
   * Inference handler entry-point. This value will override handler in MANIFEST.json if present.
   * </pre>
   *
   * <code>string handler = 2;</code>
   * @return The handler.
   */
  @java.lang.Override
  public java.lang.String getHandler() {
    java.lang.Object ref = handler_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      handler_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Inference handler entry-point. This value will override handler in MANIFEST.json if present.
   * </pre>
   *
   * <code>string handler = 2;</code>
   * @return The bytes for handler.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHandlerBytes() {
    java.lang.Object ref = handler_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      handler_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITIAL_WORKERS_FIELD_NUMBER = 3;
  private int initialWorkers_;
  /**
   * <pre>
   * Number of initial workers, default: 0.
   * </pre>
   *
   * <code>int32 initial_workers = 3;</code>
   * @return The initialWorkers.
   */
  @java.lang.Override
  public int getInitialWorkers() {
    return initialWorkers_;
  }

  public static final int MAX_BATCH_DELAY_FIELD_NUMBER = 4;
  private int maxBatchDelay_;
  /**
   * <pre>
   * Maximum delay for batch aggregation, default: 100.
   * </pre>
   *
   * <code>int32 max_batch_delay = 4;</code>
   * @return The maxBatchDelay.
   */
  @java.lang.Override
  public int getMaxBatchDelay() {
    return maxBatchDelay_;
  }

  public static final int MODEL_NAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object modelName_;
  /**
   * <pre>
   * Name of model. This value will override modelName in MANIFEST.json if present.
   * </pre>
   *
   * <code>string model_name = 5;</code>
   * @return The modelName.
   */
  @java.lang.Override
  public java.lang.String getModelName() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of model. This value will override modelName in MANIFEST.json if present.
   * </pre>
   *
   * <code>string model_name = 5;</code>
   * @return The bytes for modelName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelNameBytes() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSE_TIMEOUT_FIELD_NUMBER = 6;
  private int responseTimeout_;
  /**
   * <pre>
   * Maximum time, in seconds, the TorchServe waits for a response from the model inference code, default: 120.
   * </pre>
   *
   * <code>int32 response_timeout = 6;</code>
   * @return The responseTimeout.
   */
  @java.lang.Override
  public int getResponseTimeout() {
    return responseTimeout_;
  }

  public static final int RUNTIME_FIELD_NUMBER = 7;
  private volatile java.lang.Object runtime_;
  /**
   * <pre>
   * Runtime for the model custom service code. This value will override runtime in MANIFEST.json if present.
   * </pre>
   *
   * <code>string runtime = 7;</code>
   * @return The runtime.
   */
  @java.lang.Override
  public java.lang.String getRuntime() {
    java.lang.Object ref = runtime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      runtime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Runtime for the model custom service code. This value will override runtime in MANIFEST.json if present.
   * </pre>
   *
   * <code>string runtime = 7;</code>
   * @return The bytes for runtime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRuntimeBytes() {
    java.lang.Object ref = runtime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      runtime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYNCHRONOUS_FIELD_NUMBER = 8;
  private boolean synchronous_;
  /**
   * <pre>
   * Decides whether creation of worker synchronous or not, default: false.
   * </pre>
   *
   * <code>bool synchronous = 8;</code>
   * @return The synchronous.
   */
  @java.lang.Override
  public boolean getSynchronous() {
    return synchronous_;
  }

  public static final int URL_FIELD_NUMBER = 9;
  private volatile java.lang.Object url_;
  /**
   * <pre>
   * Model archive download url, support local file or HTTP(s) protocol.
   * </pre>
   *
   * <code>string url = 9;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Model archive download url, support local file or HTTP(s) protocol.
   * </pre>
   *
   * <code>string url = 9;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (batchSize_ != 0) {
      output.writeInt32(1, batchSize_);
    }
    if (!getHandlerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, handler_);
    }
    if (initialWorkers_ != 0) {
      output.writeInt32(3, initialWorkers_);
    }
    if (maxBatchDelay_ != 0) {
      output.writeInt32(4, maxBatchDelay_);
    }
    if (!getModelNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, modelName_);
    }
    if (responseTimeout_ != 0) {
      output.writeInt32(6, responseTimeout_);
    }
    if (!getRuntimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, runtime_);
    }
    if (synchronous_ != false) {
      output.writeBool(8, synchronous_);
    }
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, url_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (batchSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, batchSize_);
    }
    if (!getHandlerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, handler_);
    }
    if (initialWorkers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, initialWorkers_);
    }
    if (maxBatchDelay_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maxBatchDelay_);
    }
    if (!getModelNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, modelName_);
    }
    if (responseTimeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, responseTimeout_);
    }
    if (!getRuntimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, runtime_);
    }
    if (synchronous_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, synchronous_);
    }
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, url_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.pytorch.serve.grpc.management.RegisterModelRequest)) {
      return super.equals(obj);
    }
    org.pytorch.serve.grpc.management.RegisterModelRequest other = (org.pytorch.serve.grpc.management.RegisterModelRequest) obj;

    if (getBatchSize()
        != other.getBatchSize()) return false;
    if (!getHandler()
        .equals(other.getHandler())) return false;
    if (getInitialWorkers()
        != other.getInitialWorkers()) return false;
    if (getMaxBatchDelay()
        != other.getMaxBatchDelay()) return false;
    if (!getModelName()
        .equals(other.getModelName())) return false;
    if (getResponseTimeout()
        != other.getResponseTimeout()) return false;
    if (!getRuntime()
        .equals(other.getRuntime())) return false;
    if (getSynchronous()
        != other.getSynchronous()) return false;
    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getBatchSize();
    hash = (37 * hash) + HANDLER_FIELD_NUMBER;
    hash = (53 * hash) + getHandler().hashCode();
    hash = (37 * hash) + INITIAL_WORKERS_FIELD_NUMBER;
    hash = (53 * hash) + getInitialWorkers();
    hash = (37 * hash) + MAX_BATCH_DELAY_FIELD_NUMBER;
    hash = (53 * hash) + getMaxBatchDelay();
    hash = (37 * hash) + MODEL_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getModelName().hashCode();
    hash = (37 * hash) + RESPONSE_TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getResponseTimeout();
    hash = (37 * hash) + RUNTIME_FIELD_NUMBER;
    hash = (53 * hash) + getRuntime().hashCode();
    hash = (37 * hash) + SYNCHRONOUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSynchronous());
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.management.RegisterModelRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.pytorch.serve.grpc.management.RegisterModelRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.pytorch.serve.grpc.management.RegisterModelRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.pytorch.serve.grpc.management.RegisterModelRequest)
      org.pytorch.serve.grpc.management.RegisterModelRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.pytorch.serve.grpc.management.RegisterModelRequest.class, org.pytorch.serve.grpc.management.RegisterModelRequest.Builder.class);
    }

    // Construct using org.pytorch.serve.grpc.management.RegisterModelRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      batchSize_ = 0;

      handler_ = "";

      initialWorkers_ = 0;

      maxBatchDelay_ = 0;

      modelName_ = "";

      responseTimeout_ = 0;

      runtime_ = "";

      synchronous_ = false;

      url_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_RegisterModelRequest_descriptor;
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.management.RegisterModelRequest getDefaultInstanceForType() {
      return org.pytorch.serve.grpc.management.RegisterModelRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.management.RegisterModelRequest build() {
      org.pytorch.serve.grpc.management.RegisterModelRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.management.RegisterModelRequest buildPartial() {
      org.pytorch.serve.grpc.management.RegisterModelRequest result = new org.pytorch.serve.grpc.management.RegisterModelRequest(this);
      result.batchSize_ = batchSize_;
      result.handler_ = handler_;
      result.initialWorkers_ = initialWorkers_;
      result.maxBatchDelay_ = maxBatchDelay_;
      result.modelName_ = modelName_;
      result.responseTimeout_ = responseTimeout_;
      result.runtime_ = runtime_;
      result.synchronous_ = synchronous_;
      result.url_ = url_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.pytorch.serve.grpc.management.RegisterModelRequest) {
        return mergeFrom((org.pytorch.serve.grpc.management.RegisterModelRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.pytorch.serve.grpc.management.RegisterModelRequest other) {
      if (other == org.pytorch.serve.grpc.management.RegisterModelRequest.getDefaultInstance()) return this;
      if (other.getBatchSize() != 0) {
        setBatchSize(other.getBatchSize());
      }
      if (!other.getHandler().isEmpty()) {
        handler_ = other.handler_;
        onChanged();
      }
      if (other.getInitialWorkers() != 0) {
        setInitialWorkers(other.getInitialWorkers());
      }
      if (other.getMaxBatchDelay() != 0) {
        setMaxBatchDelay(other.getMaxBatchDelay());
      }
      if (!other.getModelName().isEmpty()) {
        modelName_ = other.modelName_;
        onChanged();
      }
      if (other.getResponseTimeout() != 0) {
        setResponseTimeout(other.getResponseTimeout());
      }
      if (!other.getRuntime().isEmpty()) {
        runtime_ = other.runtime_;
        onChanged();
      }
      if (other.getSynchronous() != false) {
        setSynchronous(other.getSynchronous());
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.pytorch.serve.grpc.management.RegisterModelRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.pytorch.serve.grpc.management.RegisterModelRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int batchSize_ ;
    /**
     * <pre>
     * Inference batch size, default: 1.
     * </pre>
     *
     * <code>int32 batch_size = 1;</code>
     * @return The batchSize.
     */
    @java.lang.Override
    public int getBatchSize() {
      return batchSize_;
    }
    /**
     * <pre>
     * Inference batch size, default: 1.
     * </pre>
     *
     * <code>int32 batch_size = 1;</code>
     * @param value The batchSize to set.
     * @return This builder for chaining.
     */
    public Builder setBatchSize(int value) {
      
      batchSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Inference batch size, default: 1.
     * </pre>
     *
     * <code>int32 batch_size = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchSize() {
      
      batchSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object handler_ = "";
    /**
     * <pre>
     * Inference handler entry-point. This value will override handler in MANIFEST.json if present.
     * </pre>
     *
     * <code>string handler = 2;</code>
     * @return The handler.
     */
    public java.lang.String getHandler() {
      java.lang.Object ref = handler_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        handler_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Inference handler entry-point. This value will override handler in MANIFEST.json if present.
     * </pre>
     *
     * <code>string handler = 2;</code>
     * @return The bytes for handler.
     */
    public com.google.protobuf.ByteString
        getHandlerBytes() {
      java.lang.Object ref = handler_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        handler_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Inference handler entry-point. This value will override handler in MANIFEST.json if present.
     * </pre>
     *
     * <code>string handler = 2;</code>
     * @param value The handler to set.
     * @return This builder for chaining.
     */
    public Builder setHandler(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      handler_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Inference handler entry-point. This value will override handler in MANIFEST.json if present.
     * </pre>
     *
     * <code>string handler = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHandler() {
      
      handler_ = getDefaultInstance().getHandler();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Inference handler entry-point. This value will override handler in MANIFEST.json if present.
     * </pre>
     *
     * <code>string handler = 2;</code>
     * @param value The bytes for handler to set.
     * @return This builder for chaining.
     */
    public Builder setHandlerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      handler_ = value;
      onChanged();
      return this;
    }

    private int initialWorkers_ ;
    /**
     * <pre>
     * Number of initial workers, default: 0.
     * </pre>
     *
     * <code>int32 initial_workers = 3;</code>
     * @return The initialWorkers.
     */
    @java.lang.Override
    public int getInitialWorkers() {
      return initialWorkers_;
    }
    /**
     * <pre>
     * Number of initial workers, default: 0.
     * </pre>
     *
     * <code>int32 initial_workers = 3;</code>
     * @param value The initialWorkers to set.
     * @return This builder for chaining.
     */
    public Builder setInitialWorkers(int value) {
      
      initialWorkers_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of initial workers, default: 0.
     * </pre>
     *
     * <code>int32 initial_workers = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitialWorkers() {
      
      initialWorkers_ = 0;
      onChanged();
      return this;
    }

    private int maxBatchDelay_ ;
    /**
     * <pre>
     * Maximum delay for batch aggregation, default: 100.
     * </pre>
     *
     * <code>int32 max_batch_delay = 4;</code>
     * @return The maxBatchDelay.
     */
    @java.lang.Override
    public int getMaxBatchDelay() {
      return maxBatchDelay_;
    }
    /**
     * <pre>
     * Maximum delay for batch aggregation, default: 100.
     * </pre>
     *
     * <code>int32 max_batch_delay = 4;</code>
     * @param value The maxBatchDelay to set.
     * @return This builder for chaining.
     */
    public Builder setMaxBatchDelay(int value) {
      
      maxBatchDelay_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum delay for batch aggregation, default: 100.
     * </pre>
     *
     * <code>int32 max_batch_delay = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxBatchDelay() {
      
      maxBatchDelay_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object modelName_ = "";
    /**
     * <pre>
     * Name of model. This value will override modelName in MANIFEST.json if present.
     * </pre>
     *
     * <code>string model_name = 5;</code>
     * @return The modelName.
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = modelName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of model. This value will override modelName in MANIFEST.json if present.
     * </pre>
     *
     * <code>string model_name = 5;</code>
     * @return The bytes for modelName.
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = modelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of model. This value will override modelName in MANIFEST.json if present.
     * </pre>
     *
     * <code>string model_name = 5;</code>
     * @param value The modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modelName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of model. This value will override modelName in MANIFEST.json if present.
     * </pre>
     *
     * <code>string model_name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelName() {
      
      modelName_ = getDefaultInstance().getModelName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of model. This value will override modelName in MANIFEST.json if present.
     * </pre>
     *
     * <code>string model_name = 5;</code>
     * @param value The bytes for modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modelName_ = value;
      onChanged();
      return this;
    }

    private int responseTimeout_ ;
    /**
     * <pre>
     * Maximum time, in seconds, the TorchServe waits for a response from the model inference code, default: 120.
     * </pre>
     *
     * <code>int32 response_timeout = 6;</code>
     * @return The responseTimeout.
     */
    @java.lang.Override
    public int getResponseTimeout() {
      return responseTimeout_;
    }
    /**
     * <pre>
     * Maximum time, in seconds, the TorchServe waits for a response from the model inference code, default: 120.
     * </pre>
     *
     * <code>int32 response_timeout = 6;</code>
     * @param value The responseTimeout to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTimeout(int value) {
      
      responseTimeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum time, in seconds, the TorchServe waits for a response from the model inference code, default: 120.
     * </pre>
     *
     * <code>int32 response_timeout = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseTimeout() {
      
      responseTimeout_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object runtime_ = "";
    /**
     * <pre>
     * Runtime for the model custom service code. This value will override runtime in MANIFEST.json if present.
     * </pre>
     *
     * <code>string runtime = 7;</code>
     * @return The runtime.
     */
    public java.lang.String getRuntime() {
      java.lang.Object ref = runtime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        runtime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Runtime for the model custom service code. This value will override runtime in MANIFEST.json if present.
     * </pre>
     *
     * <code>string runtime = 7;</code>
     * @return The bytes for runtime.
     */
    public com.google.protobuf.ByteString
        getRuntimeBytes() {
      java.lang.Object ref = runtime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runtime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Runtime for the model custom service code. This value will override runtime in MANIFEST.json if present.
     * </pre>
     *
     * <code>string runtime = 7;</code>
     * @param value The runtime to set.
     * @return This builder for chaining.
     */
    public Builder setRuntime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      runtime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Runtime for the model custom service code. This value will override runtime in MANIFEST.json if present.
     * </pre>
     *
     * <code>string runtime = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRuntime() {
      
      runtime_ = getDefaultInstance().getRuntime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Runtime for the model custom service code. This value will override runtime in MANIFEST.json if present.
     * </pre>
     *
     * <code>string runtime = 7;</code>
     * @param value The bytes for runtime to set.
     * @return This builder for chaining.
     */
    public Builder setRuntimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      runtime_ = value;
      onChanged();
      return this;
    }

    private boolean synchronous_ ;
    /**
     * <pre>
     * Decides whether creation of worker synchronous or not, default: false.
     * </pre>
     *
     * <code>bool synchronous = 8;</code>
     * @return The synchronous.
     */
    @java.lang.Override
    public boolean getSynchronous() {
      return synchronous_;
    }
    /**
     * <pre>
     * Decides whether creation of worker synchronous or not, default: false.
     * </pre>
     *
     * <code>bool synchronous = 8;</code>
     * @param value The synchronous to set.
     * @return This builder for chaining.
     */
    public Builder setSynchronous(boolean value) {
      
      synchronous_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Decides whether creation of worker synchronous or not, default: false.
     * </pre>
     *
     * <code>bool synchronous = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSynchronous() {
      
      synchronous_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <pre>
     * Model archive download url, support local file or HTTP(s) protocol.
     * </pre>
     *
     * <code>string url = 9;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Model archive download url, support local file or HTTP(s) protocol.
     * </pre>
     *
     * <code>string url = 9;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Model archive download url, support local file or HTTP(s) protocol.
     * </pre>
     *
     * <code>string url = 9;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Model archive download url, support local file or HTTP(s) protocol.
     * </pre>
     *
     * <code>string url = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Model archive download url, support local file or HTTP(s) protocol.
     * </pre>
     *
     * <code>string url = 9;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.pytorch.serve.grpc.management.RegisterModelRequest)
  }

  // @@protoc_insertion_point(class_scope:org.pytorch.serve.grpc.management.RegisterModelRequest)
  private static final org.pytorch.serve.grpc.management.RegisterModelRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.pytorch.serve.grpc.management.RegisterModelRequest();
  }

  public static org.pytorch.serve.grpc.management.RegisterModelRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterModelRequest>
      PARSER = new com.google.protobuf.AbstractParser<RegisterModelRequest>() {
    @java.lang.Override
    public RegisterModelRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegisterModelRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterModelRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterModelRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.pytorch.serve.grpc.management.RegisterModelRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

