// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: management.proto

package org.pytorch.serve.grpc.management;

/**
 * Protobuf type {@code org.pytorch.serve.grpc.management.ScaleWorkerRequest}
 */
public final class ScaleWorkerRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.pytorch.serve.grpc.management.ScaleWorkerRequest)
    ScaleWorkerRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScaleWorkerRequest.newBuilder() to construct.
  private ScaleWorkerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScaleWorkerRequest() {
    modelName_ = "";
    modelVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScaleWorkerRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScaleWorkerRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            modelName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            modelVersion_ = s;
            break;
          }
          case 24: {

            maxWorker_ = input.readInt32();
            break;
          }
          case 32: {

            minWorker_ = input.readInt32();
            break;
          }
          case 40: {

            numberGpu_ = input.readInt32();
            break;
          }
          case 48: {

            synchronous_ = input.readBool();
            break;
          }
          case 56: {

            timeout_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.pytorch.serve.grpc.management.ScaleWorkerRequest.class, org.pytorch.serve.grpc.management.ScaleWorkerRequest.Builder.class);
  }

  public static final int MODEL_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object modelName_;
  /**
   * <pre>
   * Name of model to scale workers.
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The modelName.
   */
  @java.lang.Override
  public java.lang.String getModelName() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of model to scale workers.
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The bytes for modelName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelNameBytes() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object modelVersion_;
  /**
   * <pre>
   * Model version.
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The modelVersion.
   */
  @java.lang.Override
  public java.lang.String getModelVersion() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Model version.
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The bytes for modelVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelVersionBytes() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAX_WORKER_FIELD_NUMBER = 3;
  private int maxWorker_;
  /**
   * <pre>
   * Maximum number of worker processes.
   * </pre>
   *
   * <code>int32 max_worker = 3;</code>
   * @return The maxWorker.
   */
  @java.lang.Override
  public int getMaxWorker() {
    return maxWorker_;
  }

  public static final int MIN_WORKER_FIELD_NUMBER = 4;
  private int minWorker_;
  /**
   * <pre>
   * Minimum number of worker processes.
   * </pre>
   *
   * <code>int32 min_worker = 4;</code>
   * @return The minWorker.
   */
  @java.lang.Override
  public int getMinWorker() {
    return minWorker_;
  }

  public static final int NUMBER_GPU_FIELD_NUMBER = 5;
  private int numberGpu_;
  /**
   * <pre>
   * Number of GPU worker processes to create.
   * </pre>
   *
   * <code>int32 number_gpu = 5;</code>
   * @return The numberGpu.
   */
  @java.lang.Override
  public int getNumberGpu() {
    return numberGpu_;
  }

  public static final int SYNCHRONOUS_FIELD_NUMBER = 6;
  private boolean synchronous_;
  /**
   * <pre>
   * Decides whether the call is synchronous or not, default: false.
   * </pre>
   *
   * <code>bool synchronous = 6;</code>
   * @return The synchronous.
   */
  @java.lang.Override
  public boolean getSynchronous() {
    return synchronous_;
  }

  public static final int TIMEOUT_FIELD_NUMBER = 7;
  private int timeout_;
  /**
   * <pre>
   * Waiting up to the specified wait time if necessary for a worker to complete all pending requests. Use 0 to terminate backend worker process immediately. Use -1 for wait infinitely.
   * </pre>
   *
   * <code>int32 timeout = 7;</code>
   * @return The timeout.
   */
  @java.lang.Override
  public int getTimeout() {
    return timeout_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getModelNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, modelName_);
    }
    if (!getModelVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, modelVersion_);
    }
    if (maxWorker_ != 0) {
      output.writeInt32(3, maxWorker_);
    }
    if (minWorker_ != 0) {
      output.writeInt32(4, minWorker_);
    }
    if (numberGpu_ != 0) {
      output.writeInt32(5, numberGpu_);
    }
    if (synchronous_ != false) {
      output.writeBool(6, synchronous_);
    }
    if (timeout_ != 0) {
      output.writeInt32(7, timeout_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getModelNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, modelName_);
    }
    if (!getModelVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, modelVersion_);
    }
    if (maxWorker_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, maxWorker_);
    }
    if (minWorker_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, minWorker_);
    }
    if (numberGpu_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, numberGpu_);
    }
    if (synchronous_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, synchronous_);
    }
    if (timeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, timeout_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.pytorch.serve.grpc.management.ScaleWorkerRequest)) {
      return super.equals(obj);
    }
    org.pytorch.serve.grpc.management.ScaleWorkerRequest other = (org.pytorch.serve.grpc.management.ScaleWorkerRequest) obj;

    if (!getModelName()
        .equals(other.getModelName())) return false;
    if (!getModelVersion()
        .equals(other.getModelVersion())) return false;
    if (getMaxWorker()
        != other.getMaxWorker()) return false;
    if (getMinWorker()
        != other.getMinWorker()) return false;
    if (getNumberGpu()
        != other.getNumberGpu()) return false;
    if (getSynchronous()
        != other.getSynchronous()) return false;
    if (getTimeout()
        != other.getTimeout()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getModelName().hashCode();
    hash = (37 * hash) + MODEL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getModelVersion().hashCode();
    hash = (37 * hash) + MAX_WORKER_FIELD_NUMBER;
    hash = (53 * hash) + getMaxWorker();
    hash = (37 * hash) + MIN_WORKER_FIELD_NUMBER;
    hash = (53 * hash) + getMinWorker();
    hash = (37 * hash) + NUMBER_GPU_FIELD_NUMBER;
    hash = (53 * hash) + getNumberGpu();
    hash = (37 * hash) + SYNCHRONOUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSynchronous());
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeout();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.pytorch.serve.grpc.management.ScaleWorkerRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.pytorch.serve.grpc.management.ScaleWorkerRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.pytorch.serve.grpc.management.ScaleWorkerRequest)
      org.pytorch.serve.grpc.management.ScaleWorkerRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.pytorch.serve.grpc.management.ScaleWorkerRequest.class, org.pytorch.serve.grpc.management.ScaleWorkerRequest.Builder.class);
    }

    // Construct using org.pytorch.serve.grpc.management.ScaleWorkerRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      modelName_ = "";

      modelVersion_ = "";

      maxWorker_ = 0;

      minWorker_ = 0;

      numberGpu_ = 0;

      synchronous_ = false;

      timeout_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.pytorch.serve.grpc.management.Management.internal_static_org_pytorch_serve_grpc_management_ScaleWorkerRequest_descriptor;
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.management.ScaleWorkerRequest getDefaultInstanceForType() {
      return org.pytorch.serve.grpc.management.ScaleWorkerRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.management.ScaleWorkerRequest build() {
      org.pytorch.serve.grpc.management.ScaleWorkerRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.management.ScaleWorkerRequest buildPartial() {
      org.pytorch.serve.grpc.management.ScaleWorkerRequest result = new org.pytorch.serve.grpc.management.ScaleWorkerRequest(this);
      result.modelName_ = modelName_;
      result.modelVersion_ = modelVersion_;
      result.maxWorker_ = maxWorker_;
      result.minWorker_ = minWorker_;
      result.numberGpu_ = numberGpu_;
      result.synchronous_ = synchronous_;
      result.timeout_ = timeout_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.pytorch.serve.grpc.management.ScaleWorkerRequest) {
        return mergeFrom((org.pytorch.serve.grpc.management.ScaleWorkerRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.pytorch.serve.grpc.management.ScaleWorkerRequest other) {
      if (other == org.pytorch.serve.grpc.management.ScaleWorkerRequest.getDefaultInstance()) return this;
      if (!other.getModelName().isEmpty()) {
        modelName_ = other.modelName_;
        onChanged();
      }
      if (!other.getModelVersion().isEmpty()) {
        modelVersion_ = other.modelVersion_;
        onChanged();
      }
      if (other.getMaxWorker() != 0) {
        setMaxWorker(other.getMaxWorker());
      }
      if (other.getMinWorker() != 0) {
        setMinWorker(other.getMinWorker());
      }
      if (other.getNumberGpu() != 0) {
        setNumberGpu(other.getNumberGpu());
      }
      if (other.getSynchronous() != false) {
        setSynchronous(other.getSynchronous());
      }
      if (other.getTimeout() != 0) {
        setTimeout(other.getTimeout());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.pytorch.serve.grpc.management.ScaleWorkerRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.pytorch.serve.grpc.management.ScaleWorkerRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object modelName_ = "";
    /**
     * <pre>
     * Name of model to scale workers.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @return The modelName.
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = modelName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of model to scale workers.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @return The bytes for modelName.
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = modelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of model to scale workers.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @param value The modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modelName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of model to scale workers.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelName() {
      
      modelName_ = getDefaultInstance().getModelName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of model to scale workers.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @param value The bytes for modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modelName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object modelVersion_ = "";
    /**
     * <pre>
     * Model version.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @return The modelVersion.
     */
    public java.lang.String getModelVersion() {
      java.lang.Object ref = modelVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Model version.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @return The bytes for modelVersion.
     */
    public com.google.protobuf.ByteString
        getModelVersionBytes() {
      java.lang.Object ref = modelVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Model version.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @param value The modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modelVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Model version.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelVersion() {
      
      modelVersion_ = getDefaultInstance().getModelVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Model version.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @param value The bytes for modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modelVersion_ = value;
      onChanged();
      return this;
    }

    private int maxWorker_ ;
    /**
     * <pre>
     * Maximum number of worker processes.
     * </pre>
     *
     * <code>int32 max_worker = 3;</code>
     * @return The maxWorker.
     */
    @java.lang.Override
    public int getMaxWorker() {
      return maxWorker_;
    }
    /**
     * <pre>
     * Maximum number of worker processes.
     * </pre>
     *
     * <code>int32 max_worker = 3;</code>
     * @param value The maxWorker to set.
     * @return This builder for chaining.
     */
    public Builder setMaxWorker(int value) {
      
      maxWorker_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum number of worker processes.
     * </pre>
     *
     * <code>int32 max_worker = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxWorker() {
      
      maxWorker_ = 0;
      onChanged();
      return this;
    }

    private int minWorker_ ;
    /**
     * <pre>
     * Minimum number of worker processes.
     * </pre>
     *
     * <code>int32 min_worker = 4;</code>
     * @return The minWorker.
     */
    @java.lang.Override
    public int getMinWorker() {
      return minWorker_;
    }
    /**
     * <pre>
     * Minimum number of worker processes.
     * </pre>
     *
     * <code>int32 min_worker = 4;</code>
     * @param value The minWorker to set.
     * @return This builder for chaining.
     */
    public Builder setMinWorker(int value) {
      
      minWorker_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Minimum number of worker processes.
     * </pre>
     *
     * <code>int32 min_worker = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinWorker() {
      
      minWorker_ = 0;
      onChanged();
      return this;
    }

    private int numberGpu_ ;
    /**
     * <pre>
     * Number of GPU worker processes to create.
     * </pre>
     *
     * <code>int32 number_gpu = 5;</code>
     * @return The numberGpu.
     */
    @java.lang.Override
    public int getNumberGpu() {
      return numberGpu_;
    }
    /**
     * <pre>
     * Number of GPU worker processes to create.
     * </pre>
     *
     * <code>int32 number_gpu = 5;</code>
     * @param value The numberGpu to set.
     * @return This builder for chaining.
     */
    public Builder setNumberGpu(int value) {
      
      numberGpu_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of GPU worker processes to create.
     * </pre>
     *
     * <code>int32 number_gpu = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberGpu() {
      
      numberGpu_ = 0;
      onChanged();
      return this;
    }

    private boolean synchronous_ ;
    /**
     * <pre>
     * Decides whether the call is synchronous or not, default: false.
     * </pre>
     *
     * <code>bool synchronous = 6;</code>
     * @return The synchronous.
     */
    @java.lang.Override
    public boolean getSynchronous() {
      return synchronous_;
    }
    /**
     * <pre>
     * Decides whether the call is synchronous or not, default: false.
     * </pre>
     *
     * <code>bool synchronous = 6;</code>
     * @param value The synchronous to set.
     * @return This builder for chaining.
     */
    public Builder setSynchronous(boolean value) {
      
      synchronous_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Decides whether the call is synchronous or not, default: false.
     * </pre>
     *
     * <code>bool synchronous = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSynchronous() {
      
      synchronous_ = false;
      onChanged();
      return this;
    }

    private int timeout_ ;
    /**
     * <pre>
     * Waiting up to the specified wait time if necessary for a worker to complete all pending requests. Use 0 to terminate backend worker process immediately. Use -1 for wait infinitely.
     * </pre>
     *
     * <code>int32 timeout = 7;</code>
     * @return The timeout.
     */
    @java.lang.Override
    public int getTimeout() {
      return timeout_;
    }
    /**
     * <pre>
     * Waiting up to the specified wait time if necessary for a worker to complete all pending requests. Use 0 to terminate backend worker process immediately. Use -1 for wait infinitely.
     * </pre>
     *
     * <code>int32 timeout = 7;</code>
     * @param value The timeout to set.
     * @return This builder for chaining.
     */
    public Builder setTimeout(int value) {
      
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Waiting up to the specified wait time if necessary for a worker to complete all pending requests. Use 0 to terminate backend worker process immediately. Use -1 for wait infinitely.
     * </pre>
     *
     * <code>int32 timeout = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeout() {
      
      timeout_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.pytorch.serve.grpc.management.ScaleWorkerRequest)
  }

  // @@protoc_insertion_point(class_scope:org.pytorch.serve.grpc.management.ScaleWorkerRequest)
  private static final org.pytorch.serve.grpc.management.ScaleWorkerRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.pytorch.serve.grpc.management.ScaleWorkerRequest();
  }

  public static org.pytorch.serve.grpc.management.ScaleWorkerRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScaleWorkerRequest>
      PARSER = new com.google.protobuf.AbstractParser<ScaleWorkerRequest>() {
    @java.lang.Override
    public ScaleWorkerRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScaleWorkerRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScaleWorkerRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScaleWorkerRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.pytorch.serve.grpc.management.ScaleWorkerRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

