// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: management.proto

package org.pytorch.serve.grpc.management;

public interface UnregisterModelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.pytorch.serve.grpc.management.UnregisterModelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of model to unregister.
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The modelName.
   */
  java.lang.String getModelName();
  /**
   * <pre>
   * Name of model to unregister.
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The bytes for modelName.
   */
  com.google.protobuf.ByteString
      getModelNameBytes();

  /**
   * <pre>
   * Name of model to unregister.
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The modelVersion.
   */
  java.lang.String getModelVersion();
  /**
   * <pre>
   * Name of model to unregister.
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The bytes for modelVersion.
   */
  com.google.protobuf.ByteString
      getModelVersionBytes();
}
