args: argparse.Namespace = ...
def cleanup(processed_file, xformed_file) -> None: ...
def create_processed_config(cci_config_file, processed_file) -> None: ...
def create_transformed_config(xformed_jb, processed_cfg, xformed_jb_name, xformed_file) -> None: ...
def print_result(res) -> None: ...
