def pypi_description() -> str: ...
class BuildFrontEnd:
    def run(self) -> None: ...

class BuildPlugins:
    def finalize_options(self) -> None: ...
    def initialize_options(self) -> None: ...
    def run(self) -> None: ...

class BuildPy:
    def run(self) -> None: ...

