package:
  name: torch-workflow-archiver
  version: "{{ environ.get('TORCH_WORKFLOW_ARCHIVER_VERSION') }}"

source:
  path: "{{ environ.get('TORCHSERVE_ROOT_DIR') }}/workflow-archiver"

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pillow
    - psutil
    - future

build:
  script: "{{ PYTHON }} -m pip install . -vv"

about:
  home: https://github.com/pytorch/serve
  summary: 'Workflow serving on PyTorch'