// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

package org.pytorch.serve.grpc.inference;

public interface PredictionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.pytorch.serve.grpc.inference.PredictionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of model.
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The modelName.
   */
  java.lang.String getModelName();
  /**
   * <pre>
   * Name of model.
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The bytes for modelName.
   */
  com.google.protobuf.ByteString
      getModelNameBytes();

  /**
   * <pre>
   * Version of model to run prediction on.
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The modelVersion.
   */
  java.lang.String getModelVersion();
  /**
   * <pre>
   * Version of model to run prediction on.
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The bytes for modelVersion.
   */
  com.google.protobuf.ByteString
      getModelVersionBytes();

  /**
   * <pre>
   * input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; input = 3;</code>
   */
  int getInputCount();
  /**
   * <pre>
   * input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; input = 3;</code>
   */
  boolean containsInput(
      java.lang.String key);
  /**
   * Use {@link #getInputMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getInput();
  /**
   * <pre>
   * input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; input = 3;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getInputMap();
  /**
   * <pre>
   * input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; input = 3;</code>
   */

  com.google.protobuf.ByteString getInputOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <pre>
   * input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; input = 3;</code>
   */

  com.google.protobuf.ByteString getInputOrThrow(
      java.lang.String key);
}
