// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

package org.pytorch.serve.grpc.inference;

/**
 * Protobuf type {@code org.pytorch.serve.grpc.inference.PredictionsRequest}
 */
public final class PredictionsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.pytorch.serve.grpc.inference.PredictionsRequest)
    PredictionsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PredictionsRequest.newBuilder() to construct.
  private PredictionsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PredictionsRequest() {
    modelName_ = "";
    modelVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PredictionsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PredictionsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            modelName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            modelVersion_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              input_ = com.google.protobuf.MapField.newMapField(
                  InputDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
            input__ = input.readMessage(
                InputDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            input_.getMutableMap().put(
                input__.getKey(), input__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionsRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetInput();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.pytorch.serve.grpc.inference.PredictionsRequest.class, org.pytorch.serve.grpc.inference.PredictionsRequest.Builder.class);
  }

  public static final int MODEL_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object modelName_;
  /**
   * <pre>
   * Name of model.
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The modelName.
   */
  @java.lang.Override
  public java.lang.String getModelName() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of model.
   * </pre>
   *
   * <code>string model_name = 1;</code>
   * @return The bytes for modelName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelNameBytes() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object modelVersion_;
  /**
   * <pre>
   * Version of model to run prediction on.
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The modelVersion.
   */
  @java.lang.Override
  public java.lang.String getModelVersion() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Version of model to run prediction on.
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The bytes for modelVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelVersionBytes() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUT_FIELD_NUMBER = 3;
  private static final class InputDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionsRequest_InputEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> input_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetInput() {
    if (input_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          InputDefaultEntryHolder.defaultEntry);
    }
    return input_;
  }

  public int getInputCount() {
    return internalGetInput().getMap().size();
  }
  /**
   * <pre>
   * input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; input = 3;</code>
   */

  @java.lang.Override
  public boolean containsInput(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetInput().getMap().containsKey(key);
  }
  /**
   * Use {@link #getInputMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getInput() {
    return getInputMap();
  }
  /**
   * <pre>
   * input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; input = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getInputMap() {
    return internalGetInput().getMap();
  }
  /**
   * <pre>
   * input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; input = 3;</code>
   */
  @java.lang.Override

  public com.google.protobuf.ByteString getInputOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetInput().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * input data for model prediction
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; input = 3;</code>
   */
  @java.lang.Override

  public com.google.protobuf.ByteString getInputOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetInput().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getModelNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, modelName_);
    }
    if (!getModelVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, modelVersion_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetInput(),
        InputDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getModelNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, modelName_);
    }
    if (!getModelVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, modelVersion_);
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetInput().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      input__ = InputDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, input__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.pytorch.serve.grpc.inference.PredictionsRequest)) {
      return super.equals(obj);
    }
    org.pytorch.serve.grpc.inference.PredictionsRequest other = (org.pytorch.serve.grpc.inference.PredictionsRequest) obj;

    if (!getModelName()
        .equals(other.getModelName())) return false;
    if (!getModelVersion()
        .equals(other.getModelVersion())) return false;
    if (!internalGetInput().equals(
        other.internalGetInput())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getModelName().hashCode();
    hash = (37 * hash) + MODEL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getModelVersion().hashCode();
    if (!internalGetInput().getMap().isEmpty()) {
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetInput().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.inference.PredictionsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.pytorch.serve.grpc.inference.PredictionsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.pytorch.serve.grpc.inference.PredictionsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.pytorch.serve.grpc.inference.PredictionsRequest)
      org.pytorch.serve.grpc.inference.PredictionsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionsRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetInput();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableInput();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.pytorch.serve.grpc.inference.PredictionsRequest.class, org.pytorch.serve.grpc.inference.PredictionsRequest.Builder.class);
    }

    // Construct using org.pytorch.serve.grpc.inference.PredictionsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      modelName_ = "";

      modelVersion_ = "";

      internalGetMutableInput().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionsRequest_descriptor;
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.inference.PredictionsRequest getDefaultInstanceForType() {
      return org.pytorch.serve.grpc.inference.PredictionsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.inference.PredictionsRequest build() {
      org.pytorch.serve.grpc.inference.PredictionsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.inference.PredictionsRequest buildPartial() {
      org.pytorch.serve.grpc.inference.PredictionsRequest result = new org.pytorch.serve.grpc.inference.PredictionsRequest(this);
      int from_bitField0_ = bitField0_;
      result.modelName_ = modelName_;
      result.modelVersion_ = modelVersion_;
      result.input_ = internalGetInput();
      result.input_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.pytorch.serve.grpc.inference.PredictionsRequest) {
        return mergeFrom((org.pytorch.serve.grpc.inference.PredictionsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.pytorch.serve.grpc.inference.PredictionsRequest other) {
      if (other == org.pytorch.serve.grpc.inference.PredictionsRequest.getDefaultInstance()) return this;
      if (!other.getModelName().isEmpty()) {
        modelName_ = other.modelName_;
        onChanged();
      }
      if (!other.getModelVersion().isEmpty()) {
        modelVersion_ = other.modelVersion_;
        onChanged();
      }
      internalGetMutableInput().mergeFrom(
          other.internalGetInput());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.pytorch.serve.grpc.inference.PredictionsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.pytorch.serve.grpc.inference.PredictionsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object modelName_ = "";
    /**
     * <pre>
     * Name of model.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @return The modelName.
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = modelName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of model.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @return The bytes for modelName.
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = modelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of model.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @param value The modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modelName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of model.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelName() {
      
      modelName_ = getDefaultInstance().getModelName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of model.
     * </pre>
     *
     * <code>string model_name = 1;</code>
     * @param value The bytes for modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modelName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object modelVersion_ = "";
    /**
     * <pre>
     * Version of model to run prediction on.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @return The modelVersion.
     */
    public java.lang.String getModelVersion() {
      java.lang.Object ref = modelVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Version of model to run prediction on.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @return The bytes for modelVersion.
     */
    public com.google.protobuf.ByteString
        getModelVersionBytes() {
      java.lang.Object ref = modelVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Version of model to run prediction on.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @param value The modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modelVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of model to run prediction on.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelVersion() {
      
      modelVersion_ = getDefaultInstance().getModelVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of model to run prediction on.
     * </pre>
     *
     * <code>string model_version = 2;</code>
     * @param value The bytes for modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modelVersion_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> input_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetInput() {
      if (input_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InputDefaultEntryHolder.defaultEntry);
      }
      return input_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetMutableInput() {
      onChanged();;
      if (input_ == null) {
        input_ = com.google.protobuf.MapField.newMapField(
            InputDefaultEntryHolder.defaultEntry);
      }
      if (!input_.isMutable()) {
        input_ = input_.copy();
      }
      return input_;
    }

    public int getInputCount() {
      return internalGetInput().getMap().size();
    }
    /**
     * <pre>
     * input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; input = 3;</code>
     */

    @java.lang.Override
    public boolean containsInput(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetInput().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInputMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getInput() {
      return getInputMap();
    }
    /**
     * <pre>
     * input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; input = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getInputMap() {
      return internalGetInput().getMap();
    }
    /**
     * <pre>
     * input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; input = 3;</code>
     */
    @java.lang.Override

    public com.google.protobuf.ByteString getInputOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetInput().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; input = 3;</code>
     */
    @java.lang.Override

    public com.google.protobuf.ByteString getInputOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetInput().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearInput() {
      internalGetMutableInput().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; input = 3;</code>
     */

    public Builder removeInput(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableInput().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getMutableInput() {
      return internalGetMutableInput().getMutableMap();
    }
    /**
     * <pre>
     * input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; input = 3;</code>
     */
    public Builder putInput(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableInput().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * input data for model prediction
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; input = 3;</code>
     */

    public Builder putAllInput(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableInput().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.pytorch.serve.grpc.inference.PredictionsRequest)
  }

  // @@protoc_insertion_point(class_scope:org.pytorch.serve.grpc.inference.PredictionsRequest)
  private static final org.pytorch.serve.grpc.inference.PredictionsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.pytorch.serve.grpc.inference.PredictionsRequest();
  }

  public static org.pytorch.serve.grpc.inference.PredictionsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictionsRequest>
      PARSER = new com.google.protobuf.AbstractParser<PredictionsRequest>() {
    @java.lang.Override
    public PredictionsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PredictionsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PredictionsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictionsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.pytorch.serve.grpc.inference.PredictionsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

