// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

package org.pytorch.serve.grpc.inference;

public interface TorchServeHealthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.pytorch.serve.grpc.inference.TorchServeHealthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * TorchServe health
   * </pre>
   *
   * <code>string health = 1;</code>
   * @return The health.
   */
  java.lang.String getHealth();
  /**
   * <pre>
   * TorchServe health
   * </pre>
   *
   * <code>string health = 1;</code>
   * @return The bytes for health.
   */
  com.google.protobuf.ByteString
      getHealthBytes();
}
