// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inference.proto

package org.pytorch.serve.grpc.inference;

/**
 * Protobuf type {@code org.pytorch.serve.grpc.inference.TorchServeHealthResponse}
 */
public final class TorchServeHealthResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.pytorch.serve.grpc.inference.TorchServeHealthResponse)
    TorchServeHealthResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TorchServeHealthResponse.newBuilder() to construct.
  private TorchServeHealthResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TorchServeHealthResponse() {
    health_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TorchServeHealthResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TorchServeHealthResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            health_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_TorchServeHealthResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_TorchServeHealthResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.pytorch.serve.grpc.inference.TorchServeHealthResponse.class, org.pytorch.serve.grpc.inference.TorchServeHealthResponse.Builder.class);
  }

  public static final int HEALTH_FIELD_NUMBER = 1;
  private volatile java.lang.Object health_;
  /**
   * <pre>
   * TorchServe health
   * </pre>
   *
   * <code>string health = 1;</code>
   * @return The health.
   */
  @java.lang.Override
  public java.lang.String getHealth() {
    java.lang.Object ref = health_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      health_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * TorchServe health
   * </pre>
   *
   * <code>string health = 1;</code>
   * @return The bytes for health.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHealthBytes() {
    java.lang.Object ref = health_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      health_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHealthBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, health_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHealthBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, health_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.pytorch.serve.grpc.inference.TorchServeHealthResponse)) {
      return super.equals(obj);
    }
    org.pytorch.serve.grpc.inference.TorchServeHealthResponse other = (org.pytorch.serve.grpc.inference.TorchServeHealthResponse) obj;

    if (!getHealth()
        .equals(other.getHealth())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEALTH_FIELD_NUMBER;
    hash = (53 * hash) + getHealth().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.pytorch.serve.grpc.inference.TorchServeHealthResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.pytorch.serve.grpc.inference.TorchServeHealthResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.pytorch.serve.grpc.inference.TorchServeHealthResponse)
      org.pytorch.serve.grpc.inference.TorchServeHealthResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_TorchServeHealthResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_TorchServeHealthResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.pytorch.serve.grpc.inference.TorchServeHealthResponse.class, org.pytorch.serve.grpc.inference.TorchServeHealthResponse.Builder.class);
    }

    // Construct using org.pytorch.serve.grpc.inference.TorchServeHealthResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      health_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_TorchServeHealthResponse_descriptor;
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.inference.TorchServeHealthResponse getDefaultInstanceForType() {
      return org.pytorch.serve.grpc.inference.TorchServeHealthResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.inference.TorchServeHealthResponse build() {
      org.pytorch.serve.grpc.inference.TorchServeHealthResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.inference.TorchServeHealthResponse buildPartial() {
      org.pytorch.serve.grpc.inference.TorchServeHealthResponse result = new org.pytorch.serve.grpc.inference.TorchServeHealthResponse(this);
      result.health_ = health_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.pytorch.serve.grpc.inference.TorchServeHealthResponse) {
        return mergeFrom((org.pytorch.serve.grpc.inference.TorchServeHealthResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.pytorch.serve.grpc.inference.TorchServeHealthResponse other) {
      if (other == org.pytorch.serve.grpc.inference.TorchServeHealthResponse.getDefaultInstance()) return this;
      if (!other.getHealth().isEmpty()) {
        health_ = other.health_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.pytorch.serve.grpc.inference.TorchServeHealthResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.pytorch.serve.grpc.inference.TorchServeHealthResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object health_ = "";
    /**
     * <pre>
     * TorchServe health
     * </pre>
     *
     * <code>string health = 1;</code>
     * @return The health.
     */
    public java.lang.String getHealth() {
      java.lang.Object ref = health_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        health_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * TorchServe health
     * </pre>
     *
     * <code>string health = 1;</code>
     * @return The bytes for health.
     */
    public com.google.protobuf.ByteString
        getHealthBytes() {
      java.lang.Object ref = health_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        health_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * TorchServe health
     * </pre>
     *
     * <code>string health = 1;</code>
     * @param value The health to set.
     * @return This builder for chaining.
     */
    public Builder setHealth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      health_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TorchServe health
     * </pre>
     *
     * <code>string health = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHealth() {
      
      health_ = getDefaultInstance().getHealth();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * TorchServe health
     * </pre>
     *
     * <code>string health = 1;</code>
     * @param value The bytes for health to set.
     * @return This builder for chaining.
     */
    public Builder setHealthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      health_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.pytorch.serve.grpc.inference.TorchServeHealthResponse)
  }

  // @@protoc_insertion_point(class_scope:org.pytorch.serve.grpc.inference.TorchServeHealthResponse)
  private static final org.pytorch.serve.grpc.inference.TorchServeHealthResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.pytorch.serve.grpc.inference.TorchServeHealthResponse();
  }

  public static org.pytorch.serve.grpc.inference.TorchServeHealthResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TorchServeHealthResponse>
      PARSER = new com.google.protobuf.AbstractParser<TorchServeHealthResponse>() {
    @java.lang.Override
    public TorchServeHealthResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TorchServeHealthResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TorchServeHealthResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TorchServeHealthResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.pytorch.serve.grpc.inference.TorchServeHealthResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

