def _retrieve_buffer(conn, length) -> bytearray: ...
def _retrieve_input_data(conn) -> typing.Optional[typing.Dict[str, typing.Any]]: ...
def _retrieve_load_msg(conn) -> typing.Dict[str, typing.Any]: ...
def _retrieve_reqest_header(conn) -> typing.Optional[typing.Dict[str, typing.Any]]: ...
def create_load_model_response(code, message) -> bytearray: ...
def encode_response_headers(resp_hdr_map) -> bytearray: ...
