name: 📚 Docs
description: Report an issue related to documentation

body:
  - type: textarea
    attributes:
      label: 📚 The doc issue
      description: >
        A clear and concise description of what content in https://pytorch.org/serve is an issue. If this has to do with
        the general https://pytorch.org website, please file an issue at
        https://github.com/pytorch/pytorch.github.io/issues/new/choose instead. And if this has to do with pytorch.org/tutorials, please file an issue with https://github.com/pytorch/tutorials/issues/new/choose
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggest a potential alternative/fix
      description: >
        Tell us how we could improve the documentation in this regard.
  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!