class DummyNodeService:
    def _inference(self, data) -> None: ...
    def inference(self) -> None: ...
    def ping(self) -> None: ...
    def signature(self) -> None: ...

class SomeOtherClass:
    def __init__(self) -> None: ...

