FROM pytorch/torchserve-nightly:latest-gpu as server

RUN pip install vllm==0.5.2

USER root

RUN mkdir /data && chown -R model-server /data

USER model-server

ENTRYPOINT [ "python", "-m", "ts.llm_launcher", "--vllm_engine.download_dir", "/data" ]
