class Model:
    def __init__(self, model_name, serialized_file, handler, model_file=None, model_version=None, extensions=None, requirements_file=None) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

