def collect_all(mod) -> None: ...
def cpu_utilization() -> None: ...
def disk_available() -> None: ...
def disk_used() -> None: ...
def disk_utilization() -> None: ...
def memory_available() -> None: ...
def memory_used() -> None: ...
def memory_utilization() -> None: ...
