class TestModelPackaging:
    def patches(self, mocker) -> model-archiver.model_archiver.tests.unit_tests.test_model_packaging.TestModelPackaging.patches.Patches: ...
    def test_export_model_method(self, patches) -> None: ...
    def test_export_model_method_noarchive(self, patches) -> None: ...
    def test_export_model_method_tar(self, patches) -> None: ...
    def test_gen_model_archive(self, patches) -> None: ...

