args: argparse.Namespace = ...
image: io.BufferedReader = ...
image_read: bytes = ...
image_64_encode: bytes = ...
bytes_array: str = ...
request: typing.Dict[str, typing.List[typing.Dict[str, str]]] = ...
