minWorkers: 1
maxWorkers: 1
maxBatchDelay: 200
responseTimeout: 300
deviceType: "gpu"
max_response_size: 655350000
handler:
    model_weights: "./diffusion-fast-model"
    num_inference_steps: 30
    compile_unet: true
    compile_mode: "max-autotune"
    compile_vae: true
    enable_fused_projections: true
    do_quant: "int8dynamic"
    change_comp_config: true
