class MockContext:
    def __init__(self, model_pt_file: str = "model.pt", model_dir: str = "ts/torch_handler/unit_tests/models/tmp", model_file: str = "model.py", gpu_id: str = "0", model_name: str = "mnist") -> None: ...
    def get_request_header(self, idx, exp) -> bool: ...

