package:
  name: torch-model-archiver
  version: 0.0.1b20200409

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pillow
    - psutil
    - future

build:
  noarch: generic
  script_env:
    - TORCH_MODEL_ARCHIVER_WHEEL

about:
  home: https://github.com/pytorch/serve
  summary: 'Model serving on PyTorch'
