def model_context() -> ts.torch_handler.unit_tests.test_utils.mock_context.MockContext: ...
def test_batch_handle(model_context) -> None: ...
def test_initialize(model_context) -> ts.torch_handler.base_handler.BaseHandler: ...
def test_single_handle(model_context) -> None: ...
