def model_setup() -> typing.Tuple[ts.torch_handler.unit_tests.test_utils.mock_context.MockContext, bytes]: ...
def test_handle(model_setup) -> None: ...
def test_handle_explain(model_setup) -> None: ...
def test_initialize(model_setup) -> ts.torch_handler.image_classifier.ImageClassifier: ...
