def model_setup() -> typing.Tuple[ts.torch_handler.unit_tests.test_utils.mock_context.MockContext, bytes]: ...
def test_handle(model_setup) -> None: ...
def test_handle_kf(model_setup) -> None: ...
def test_initialize(model_setup) -> examples.image_classifier.mnist.mnist_handler.MNISTDigitClassifier: ...
def test_initialize_kf(model_setup) -> ts.torch_handler.request_envelope.kserve.KServeEnvelope: ...
