def model_context() -> ts.torch_handler.unit_tests.test_utils.mock_context.MockContext: ...
def test_binary(model_context) -> None: ...
def test_body(handle_fn, model_context) -> None: ...
def test_json(handle_fn, model_context) -> None: ...
def test_json_batch(handle_fn, model_context) -> None: ...
def test_json_double_batch(handle_fn, model_context) -> None: ...
