latex_documents: typing.List[typing.Tuple[str, ...]] = ...
man_pages: typing.List[typing.Tuple[str, str, str, typing.List[str], int]] = ...
texinfo_documents: typing.List[typing.Tuple[str, ...]] = ...
intersphinx_mapping: typing.Dict[str, typing.Tuple[str, None]] = ...
def setup(app) -> None: ...
