LOGGER: logging.Logger = ...
args: argparse.Namespace = ...
class S3BinaryUploader:
    def __init__(self, s3_bucket, is_dryrun=False, is_nightly=False) -> None: ...
    def s3_upload_default_binaries(self) -> None: ...
    def s3_upload_local_folder(self, local_folder_path) -> None: ...

