logger: logging.Logger = ...
def emit_metrics(metrics) -> None: ...
class Service:
    def __init__(self, model_name, model_dir, manifest, entry_point, gpu, batch_size, limit_max_image_pixels: bool = True) -> None: ...
    def context(self) -> ts.context.Context: ...

