kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: torchserve
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: torchserve
  # autoscale between 1 and 10 replicas
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metricName: ts_queue_latency_microseconds
      targetValue: "7000000m"
