class ASPP:
    def __init__(self, in_channels, atrous_rates, out_channels: int = 256) -> None: ...

class ASPPConv:
    def __init__(self, in_channels, out_channels, dilation) -> None: ...

class ASPPPooling:
    def __init__(self, in_channels, out_channels) -> None: ...

class DeepLabHead:
    def __init__(self, in_channels, num_classes) -> None: ...

