minWorkers: 1
maxWorkers: 4
maxBatchDelay: 200
responseTimeout: 3600
deviceType: "cpu"
pt2:
  backend: "openvino"
  options:
    device: "CPU"
    model_caching: true
    cache_dir: "./sd_model_cache"
    config:
      PERFORMANCE_HINT: "LATENCY"
handler:
    profile: true
    model_path: "model"
    num_inference_steps: 5
    compile_unet: true
    compile_mode: "max-autotune"
    compile_vae: true
    enable_fused_projections: true
    do_quant: false
    change_comp_config: false
    no_bf16: true
    no_sdpa: false
    upcast_vae: false
    is_xl: true
    is_lcm: true
