#!/bin/bash
set -euo pipefail

source scripts/intall_utils

echo "                      =============================================="
echo "                      If you are within a conda env please deactivate it and come back"
echo "                      If you don't want to proceed kill this script in the next 10 seconds!"
echo "                      =============================================="

sleep 10

install_java_deps_mac()
{
	brew tap AdoptOpenJDK/openjdk
	brew cask install adoptopenjdk11
}

clean_slate
install_java_deps_mac
install_torch_deps

build_install_server
build_install_archiver
