apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-store-claim
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 700Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
