# Build Spec for AWS CodeBuild CI

version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl gnupg2
      - pip install pip -U
      - pip install -r ci/requirements.txt

  build:
    commands:
      - ./torchserve_sanity.sh
      - cd serving-sdk/ && mvn clean install && cd ../
