# Build Spec for AWS CodeBuild CI

version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl
      - pip install pip -U
      - pip install future
      - pip install Pillow
      - pip install pytest
      - pip install wheel
      - pip install twine
      - pip install pytest-mock -U
      - pip install requests
      - pip install -U -e .[torch]
      - cd model-archiver/ && pip install -U -e . && cd ../

  build:
    commands:
      - frontend/gradlew -p frontend build
      - python -m pytest mms/tests/unit_tests
      - cd model-archiver/ && python -m pytest model_archiver/tests/unit_tests && cd ../
      - cd model-archiver/ && python -m pytest model_archiver/tests/integ_tests && cd ../
      - cd serving-sdk/ && mvn clean deploy && cd ../
      - pylint -rn --rcfile=./mms/tests/pylintrc mms/.
      - cd model-archiver/ && pylint -rn --rcfile=./model_archiver/tests/pylintrc model_archiver/. && cd ../
      - $NIGHTLYBUILD
      - eval $NIGHTLYUPLOAD

artifacts:
  files:
    - dist/*.whl
    - model_archiver/dist/*.whl
    - frontend/server/build/reports/**/*
    - frontend/modelarchive/build/reports/**/*
