# Build Spec for AWS CodeBuild CI

version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl
      - pip install pip -U
      - pip install -r requirements.txt

  build:
    commands:
      - ./torchserve_sanity.sh
      - cd serving-sdk/ && mvn clean deploy && cd ../

artifacts:
  files:
    - dist/*.whl
    - model_archiver/dist/*.whl
    - frontend/server/build/reports/**/*
    - frontend/modelarchive/build/reports/**/*
    - frontend/cts/build/reports/**/*
