package:
  name: torchserve
  version: "{{ environ.get('TORCHSERVE_VERSION') }}"

source:
  path: "{{ environ.get('TORCHSERVE_ROOT_DIR') }}"

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pillow
    - psutil
    - future

build:
  script: "{{ PYTHON }} -m pip install . -vv"

about:
  home: https://github.com/pytorch/serve
  summary: 'Model serving on PyTorch'
