def build_cmd(test) -> str: ...
def create_file_path(path: typing.Union[os.PathLike[bytes], os.PathLike[str], bytes, str]) -> None: ...
def delete_file_path(path: typing.Union[os.PathLike[bytes], os.PathLike[str], bytes, str]) -> None: ...
def run_test(test, cmd) -> int: ...
def test_workflow_archiver() -> None: ...
def validate(test) -> None: ...
def validate_archive_exists(test) -> None: ...
def validate_manifest_file(manifest, test) -> None: ...
def validate_war_archive(test) -> None: ...
