logger: logging.Logger = ...
class NewsClassifierHandler:
    def __init__(self) -> None: ...
    def add_attributions_to_visualizer(self, attributions, tokens, pred_prob, pred_class, true_class, attr_class, delta, vis_data_records) -> None: ...
    def explain_handle(self, model_wraper, text, target: int = 1) -> typing.List[typing.Dict[str, typing.Any]]: ...
    def initialize(self, ctx) -> None: ...

