logger: logging.Logger = ...
class WaveGlowSpeechSynthesizer:
    def __init__(self) -> None: ...
    def _load_tacotron2_model(self, model_dir) -> None: ...
    def initialize(self, ctx) -> None: ...
    def postprocess(self, inference_output) -> typing.List[bytes]: ...

