class Invertible1x1Conv:
    def __init__(self, c) -> None: ...
    def forward(self, z, reverse: bool = False): ...

class WN:
    def __init__(self, n_in_channels: int, n_mel_channels, n_layers, n_channels, kernel_size) -> None: ...

class WaveGlow:
    def __init__(self, n_mel_channels, n_flows, n_group, n_early_every, n_early_size, WN_config) -> None: ...
    def infer(self, spect, sigma: float = 1.000000): ...

