CONDA_BINARY: str = ...
args: argparse.Namespace = ...
def conda_build(ts_wheel_path, ma_wheel_path, wa_wheel_path) -> int: ...
def install_conda_build() -> None: ...
def install_miniconda() -> typing.Optional[int]: ...
