minWorkers: 4
maxWorkers: 4
responseTimeout: 600
pt2:
  compile:
    enable: True
    backend: inductor
    mode: max-autotune
handler:
  torch_inductor_caching:
    torch_inductor_fx_graph_cache: true
