class TestEmitMetrics:
    def test_emit_metrics(self, caplog) -> None: ...

class TestService:
    def service(self, mocker) -> ts.service.Service: ...
    def test_predict(self, service, mocker) -> None: ...
    def test_valid_req(self, service) -> None: ...
    def test_with_nil_request(self, service) -> None: ...

