def socket_patches(mocker) -> ts.tests.unit_tests.test_otf_codec_protocol.socket_patches.Patches: ...
class TestOtfCodecHandler:
    def test_create_load_model_response(self) -> None: ...
    def test_create_predict_response(self) -> None: ...
    def test_create_predict_response_with_error(self) -> None: ...
    def test_retrieve_msg_load_gpu(self, socket_patches) -> None: ...
    def test_retrieve_msg_load_no_gpu(self, socket_patches) -> None: ...
    def test_retrieve_msg_predict(self, socket_patches) -> None: ...
    def test_retrieve_msg_predict_binary(self, socket_patches) -> None: ...
    def test_retrieve_msg_predict_text(self, socket_patches) -> None: ...
    def test_retrieve_msg_unknown(self, socket_patches) -> None: ...

