logger: logging.Logger = ...
class LanguageTranslationHandler:
    def __init__(self) -> None: ...
    def inference(self, data, *args, **kwargs) -> typing.List[str]: ...
    def initialize(self, context) -> None: ...

