name: Benchmark torchserve inf1 nightly

on:
  # run every day at 2:15am
  #schedule:
  #  - cron:  '15 02 * * *'
  # test workflow before merge
  push:

jobs:
  nightly:
    runs-on: [self-hosted, inf1]
    timeout-minutes: 1320
    steps:
      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          cd $RUNNER_WORKSPACE
          pwd
          cd ..
          pwd
          rm -rf _tool
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
            sudo apt-get update -y
            sudo apt-get install -y apache2-utils
            pip install -r benchmarks/requirements-ab.txt
            export omp_num_threads=1
      - name: Benchmark inf1 nightly
        env:
          NEURON_RT_NUM_CORES: '4'
        run: python benchmarks/auto_benchmark.py --input benchmarks/benchmark_config_neuron.yaml --skip false
      - name: Save benchmark artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nightly inf1 artifact
          path: /tmp/ts_benchmark
      - name: Open issue on failure
        if: ${{ failure() && github.event_name  == 'schedule' }}
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Nightly INF1 benchmark failed
          body:  Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed, please check why
          assignees: ''
