name: CI CPU Graviton

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:


concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-cpu:
    runs-on: [self-hosted, graviton-test]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: arm64
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev
      - name: Torchserve Sanity
        uses: nick-fields/retry@v3
        env:
          TS_MAC_ARM64_CPU_ONLY: 'True'
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_on: error
          command: |
            python torchserve_sanity.py
