  mypy:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mypy
        run: |
          pip install mypy
      - name: Run mypy
        env:
          MYPY_FORCE_COLOR: 1
          TERM: xterm-color
        run: |
          set -eux
          STATUS=
          if ! mypy --config=mypy.ini; then
            STATUS=fail
          fi
          if [ -n "$STATUS" ]; then
            echo 'Please fix the above mypy warnings.'
            false
          fi
