name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Install mypy
        run: |
          pip install mypy
      - name: Run mypy
        env:
          MYPY_FORCE_COLOR: 1
          TERM: xterm-color
        run: |
          set -eux
          STATUS=
          if ! mypy --config=mypy.ini; then
            STATUS=fail
          fi
          if [ -n "$STATUS" ]; then
            echo 'Please fix the above mypy warnings.'
            false
          fi
