name: Run Regression Tests for GPU nightly binaries

on:
  # run every day at 6:15am
  schedule:
    - cron:  '15 6 * * *'
  merge_group:

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  regression-gpu-nightly-binaries:
    # creates workflows for OS: ubuntu, macOS
    runs-on: [self-hosted, regression-test-gpu]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        binaries: ["pypi", "conda"]
    steps:
      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          ls -la ./
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: conda --version
      - run: python --version
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev --cuda=cu118
      - name: Torchserve Regression Tests
        run: |
          python test/regression_tests.py --binaries --${{ matrix.binaries }} --nightly
