name: Run Regression Tests for GPU nightly binaries

on:
  # run every day at 6:15am
  schedule:
    - cron:  '15 6 * * *'

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  regression-gpu-nightly-binaries:
    # creates workflows for 3 python versions on self hosted
    runs-on: [self-hosted, regression-test-gpu]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        binaries: ["pypi", "conda"]
    steps:
      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          ls -la ./
      - name: Checkout TorchServe
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python --version
      - run: conda --version
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          echo "=====CHECK ENV AND PYTHON VERSION===="
          /home/ubuntu/actions-runner/_work/serve/serve/3/condabin/conda info --envs
          python --version
          echo "=====RUN INSTALL DEPENDENCIES===="
          python ts_scripts/install_dependencies.py --environment=dev --cuda=cu121
      - name: Torchserve Regression Tests
        shell: bash -el {0}
        run: |
          echo "=====CHECK ENV AND PYTHON VERSION===="
          /home/ubuntu/actions-runner/_work/serve/serve/3/condabin/conda info --envs
          python --version
          echo "=====RUN REGRESSION TESTS===="
          python test/regression_tests.py --binaries --${{ matrix.binaries }} --nightly
