name: Push torch-model-archiver-nightly

on:
  # run every day at 11:15am
  schedule:
    - cron:  '15 11 * * *'
jobs:
  nightly:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchServe
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -eux
          pip install twine wheel
      - name: Push nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        working-directory: model-archiver
        run: ../ts_scripts/push_nightly.sh torch-model-archiver-nightly
