kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-store-claim
spec:
  storageClassName: persistent-volume-azurefile
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi